// Dados de demonstração simulando resposta da API Pluggy
// Estes dados são baseados no formato real da API Pluggy Sandbox

import type { PluggyAccount, PluggyTransaction, PluggyInvestment, PluggyIdentity } from "./client"

// Conta de demonstração (Sandbox Pluggy)
export const demoAccounts: PluggyAccount[] = [
  {
    id: "acc_demo_001",
    itemId: "item_demo_001",
    type: "BANK",
    subtype: "CHECKING_ACCOUNT",
    name: "Conta Corrente",
    balance: 15750.42,
    currencyCode: "BRL",
    number: "12345-6",
    marketingName: "Nubank Conta",
    owner: "João Silva Demo",
    bankData: {
      transferNumber: "0001",
      closingBalance: 15750.42,
    },
  },
  {
    id: "acc_demo_002",
    itemId: "item_demo_001",
    type: "BANK",
    subtype: "SAVINGS_ACCOUNT",
    name: "Conta Poupança",
    balance: 8320.15,
    currencyCode: "BRL",
    number: "12345-7",
    marketingName: "Nubank Poupança",
    owner: "João Silva Demo",
  },
  {
    id: "acc_demo_003",
    itemId: "item_demo_002",
    type: "CREDIT",
    subtype: "CREDIT_CARD",
    name: "Cartão de Crédito",
    balance: -2450.8,
    currencyCode: "BRL",
    number: "****1234",
    marketingName: "Nubank Roxinho",
    owner: "João Silva Demo",
  },
]

// Transações de demonstração
export const demoTransactions: PluggyTransaction[] = [
  {
    id: "txn_demo_001",
    accountId: "acc_demo_001",
    description: "PIX Recebido - Salário",
    descriptionRaw: "PIX RECEBIDO",
    currencyCode: "BRL",
    amount: 8500.0,
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    balance: 15750.42,
    category: "Salário",
    categoryId: "cat_salary",
    type: "CREDIT",
    status: "POSTED",
    paymentData: {
      payer: {
        name: "Empresa XPTO Ltda",
        documentNumber: "12.345.678/0001-90",
      },
    },
  },
  {
    id: "txn_demo_002",
    accountId: "acc_demo_001",
    description: "iFood",
    descriptionRaw: "IFOOD *RESTAURANTE",
    currencyCode: "BRL",
    amount: -45.9,
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    balance: 15704.52,
    category: "Alimentação",
    categoryId: "cat_food",
    type: "DEBIT",
    status: "POSTED",
  },
  {
    id: "txn_demo_003",
    accountId: "acc_demo_001",
    description: "Uber",
    descriptionRaw: "UBER *TRIP",
    currencyCode: "BRL",
    amount: -32.5,
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    balance: 15672.02,
    category: "Transporte",
    categoryId: "cat_transport",
    type: "DEBIT",
    status: "POSTED",
  },
  {
    id: "txn_demo_004",
    accountId: "acc_demo_001",
    description: "Spotify Premium",
    descriptionRaw: "SPOTIFY",
    currencyCode: "BRL",
    amount: -21.9,
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    balance: 15650.12,
    category: "Assinaturas",
    categoryId: "cat_subscription",
    type: "DEBIT",
    status: "POSTED",
  },
  {
    id: "txn_demo_005",
    accountId: "acc_demo_001",
    description: "Netflix",
    descriptionRaw: "NETFLIX.COM",
    currencyCode: "BRL",
    amount: -55.9,
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    balance: 15594.22,
    category: "Assinaturas",
    categoryId: "cat_subscription",
    type: "DEBIT",
    status: "POSTED",
  },
  {
    id: "txn_demo_006",
    accountId: "acc_demo_001",
    description: "PIX Enviado - Aluguel",
    descriptionRaw: "PIX ENVIADO",
    currencyCode: "BRL",
    amount: -2200.0,
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    balance: 13394.22,
    category: "Moradia",
    categoryId: "cat_housing",
    type: "DEBIT",
    status: "POSTED",
    paymentData: {
      receiver: {
        name: "Imobiliária Central",
        documentNumber: "98.765.432/0001-10",
      },
    },
  },
  {
    id: "txn_demo_007",
    accountId: "acc_demo_001",
    description: "Supermercado Extra",
    descriptionRaw: "EXTRA HIPERMERCADO",
    currencyCode: "BRL",
    amount: -387.45,
    date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    balance: 13006.77,
    category: "Alimentação",
    categoryId: "cat_food",
    type: "DEBIT",
    status: "POSTED",
  },
  {
    id: "txn_demo_008",
    accountId: "acc_demo_001",
    description: "Farmácia Drogasil",
    descriptionRaw: "DROGASIL",
    currencyCode: "BRL",
    amount: -156.8,
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    balance: 12849.97,
    category: "Saúde",
    categoryId: "cat_health",
    type: "DEBIT",
    status: "POSTED",
  },
  {
    id: "txn_demo_009",
    accountId: "acc_demo_001",
    description: "Amazon Prime",
    descriptionRaw: "AMAZON PRIME",
    currencyCode: "BRL",
    amount: -14.9,
    date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    balance: 12835.07,
    category: "Assinaturas",
    categoryId: "cat_subscription",
    type: "DEBIT",
    status: "POSTED",
  },
  {
    id: "txn_demo_010",
    accountId: "acc_demo_001",
    description: "PIX Recebido - Freelance",
    descriptionRaw: "PIX RECEBIDO",
    currencyCode: "BRL",
    amount: 2500.0,
    date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    balance: 15335.07,
    category: "Renda Extra",
    categoryId: "cat_extra_income",
    type: "CREDIT",
    status: "POSTED",
  },
  {
    id: "txn_demo_011",
    accountId: "acc_demo_003",
    description: "Restaurante Outback",
    descriptionRaw: "OUTBACK STEAKHOUSE",
    currencyCode: "BRL",
    amount: -245.6,
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    balance: -2450.8,
    category: "Alimentação",
    categoryId: "cat_food",
    type: "DEBIT",
    status: "POSTED",
  },
  {
    id: "txn_demo_012",
    accountId: "acc_demo_003",
    description: "Magazine Luiza",
    descriptionRaw: "MAGALU",
    currencyCode: "BRL",
    amount: -899.9,
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    balance: -2205.2,
    category: "Compras",
    categoryId: "cat_shopping",
    type: "DEBIT",
    status: "POSTED",
  },
]

// Investimentos de demonstração
export const demoInvestments: PluggyInvestment[] = [
  {
    id: "inv_demo_001",
    itemId: "item_demo_001",
    name: "Tesouro Selic 2029",
    type: "FIXED_INCOME",
    subtype: "TREASURY",
    balance: 25000.0,
    currencyCode: "BRL",
    value: 26750.45,
    annualRate: 13.25,
    lastMonthRate: 1.02,
    dueDate: "2029-03-01",
    issuer: "Tesouro Nacional",
    institution: {
      name: "Nubank",
      cnpj: "18.236.120/0001-58",
    },
  },
  {
    id: "inv_demo_002",
    itemId: "item_demo_001",
    name: "CDB Banco Inter 110%",
    type: "FIXED_INCOME",
    subtype: "CDB",
    balance: 10000.0,
    currencyCode: "BRL",
    value: 11234.56,
    annualRate: 14.58,
    lastMonthRate: 1.12,
    dueDate: "2026-06-15",
    issuer: "Banco Inter",
    issuerCnpj: "00.416.968/0001-01",
    institution: {
      name: "Nubank",
      cnpj: "18.236.120/0001-58",
    },
  },
  {
    id: "inv_demo_003",
    itemId: "item_demo_001",
    name: "LCI Caixa 95%",
    type: "FIXED_INCOME",
    subtype: "LCI",
    balance: 15000.0,
    currencyCode: "BRL",
    value: 16125.3,
    annualRate: 12.35,
    lastMonthRate: 0.95,
    dueDate: "2025-12-20",
    issuer: "Caixa Econômica Federal",
    issuerCnpj: "00.360.305/0001-04",
    institution: {
      name: "Nubank",
      cnpj: "18.236.120/0001-58",
    },
  },
  {
    id: "inv_demo_004",
    itemId: "item_demo_001",
    name: "Fundo Multimercado XP",
    type: "MUTUAL_FUND",
    subtype: "MULTIMARKET",
    balance: 8000.0,
    currencyCode: "BRL",
    value: 8456.78,
    quantity: 8.234,
    annualRate: 18.45,
    lastMonthRate: 1.45,
    institution: {
      name: "XP Investimentos",
      cnpj: "02.332.886/0001-04",
    },
  },
  {
    id: "inv_demo_005",
    itemId: "item_demo_001",
    name: "PETR4 - Petrobras PN",
    type: "EQUITY",
    subtype: "STOCK",
    number: "PETR4",
    balance: 5000.0,
    currencyCode: "BRL",
    value: 5890.5,
    quantity: 150,
    lastMonthRate: 3.25,
    institution: {
      name: "Clear Corretora",
      cnpj: "02.332.886/0001-04",
    },
  },
  {
    id: "inv_demo_006",
    itemId: "item_demo_001",
    name: "IVVB11 - ETF S&P 500",
    type: "ETF",
    subtype: "ETF",
    number: "IVVB11",
    balance: 12000.0,
    currencyCode: "BRL",
    value: 13450.2,
    quantity: 45,
    lastMonthRate: 2.15,
    institution: {
      name: "Clear Corretora",
      cnpj: "02.332.886/0001-04",
    },
  },
]

// Identidade de demonstração
export const demoIdentity: PluggyIdentity = {
  id: "ident_demo_001",
  itemId: "item_demo_001",
  fullName: "João Silva Demo",
  cpf: "123.456.789-00",
  birthDate: "1990-05-15",
  email: "joao.demo@email.com",
  phoneNumber: "+55 11 99999-9999",
  addresses: [
    {
      fullAddress: "Rua das Flores, 123 - Apto 45",
      city: "São Paulo",
      state: "SP",
      country: "Brasil",
      postalCode: "01310-100",
    },
  ],
}

// Dados agregados para gráficos
export const demoSpendingByCategory = [
  { name: "Alimentação", value: 679.95, color: "#ef4444" },
  { name: "Moradia", value: 2200.0, color: "#f97316" },
  { name: "Transporte", value: 32.5, color: "#eab308" },
  { name: "Assinaturas", value: 92.7, color: "#22c55e" },
  { name: "Saúde", value: 156.8, color: "#06b6d4" },
  { name: "Compras", value: 899.9, color: "#8b5cf6" },
]

export const demoMonthlyFlow = [
  { month: "Jul", income: 8500, expense: 6200 },
  { month: "Ago", income: 9200, expense: 7100 },
  { month: "Set", income: 8800, expense: 6800 },
  { month: "Out", income: 9500, expense: 7300 },
  { month: "Nov", income: 11000, expense: 8200 },
  { month: "Dez", income: 11000, expense: 4061.85 },
]

// Resumo do portfólio
export const demoPortfolioSummary = {
  totalBalance: demoAccounts.reduce((sum, acc) => sum + Math.max(0, acc.balance), 0),
  totalInvestments: demoInvestments.reduce((sum, inv) => sum + inv.value, 0),
  totalDebt: Math.abs(demoAccounts.filter((acc) => acc.balance < 0).reduce((sum, acc) => sum + acc.balance, 0)),
  netWorth: 0, // Calculado abaixo
}

demoPortfolioSummary.netWorth =
  demoPortfolioSummary.totalBalance + demoPortfolioSummary.totalInvestments - demoPortfolioSummary.totalDebt
